name = "job-site"
type = "webpack"
account_id = "be5f536561f711e8e7798e46807f0d3b"
workers_dev = true

[build]
command = "npm run build" # If you need to build your Workers script

[site]
bucket = "./client/build" # Set this to the build directory of your React app
entry-point = "workers-site"

[env.production]
name = "PRODUCTION"
